const TelegramBot = require('node-telegram-bot-api');
const fs = require('fs');
const path = require('path');
const archiver = require('archiver');

// Replace with your actual bot token
const TOKEN = 'YOUR_TELEGRAM_BOT_TOKEN';

const bot = new TelegramBot(TOKEN, { polling: true });

// Store user project data temporarily
const userProjects = {};

bot.onText(/\/start/, (msg) => {
    const chatId = msg.chat.id;
    bot.sendMessage(chatId, 'مرحباً بك في بوت إنشاء المشاريع بالذكاء الاصطناعي! أرسل لي /newproject لبدء مشروع جديد.');
});

bot.onText(/\/newproject/, (msg) => {
    const chatId = msg.chat.id;
    userProjects[chatId] = { state: 'awaiting_name' };
    bot.sendMessage(chatId, 'أهلاً بك! ما هو اسم مشروعك؟');
});

bot.on('message', async (msg) => {
    const chatId = msg.chat.id;
    const text = msg.text;

    if (text.startsWith('/')) {
        // Ignore commands, they are handled by onText
        return;
    }

    if (userProjects[chatId] && userProjects[chatId].state === 'awaiting_name') {
        userProjects[chatId].projectName = text;
        userProjects[chatId].state = 'awaiting_description';
        bot.sendMessage(chatId, `تم تعيين اسم المشروع: "${text}". الآن، يرجى إرسال وصف مفصل للمشروع الذي تريده.`);
    } else if (userProjects[chatId] && userProjects[chatId].state === 'awaiting_description') {
        userProjects[chatId].projectDescription = text;
        userProjects[chatId].state = 'processing';
        bot.sendMessage(chatId, `شكراً لك! مشروعك "${userProjects[chatId].projectName}" قيد الإنشاء الآن. قد يستغرق هذا بعض الوقت...`);

        // --- AI Integration and Project Creation Logic (Placeholder) ---
        try {
            const projectDetails = await generateProject(userProjects[chatId].projectName, userProjects[chatId].projectDescription);
            const projectPath = await createProjectFiles(userProjects[chatId].projectName, projectDetails);
            const zipFilePath = await zipProject(projectPath);

            // Send the zipped project and details to the user
            await bot.sendDocument(chatId, zipFilePath, {
                caption: `مشروعك "${userProjects[chatId].projectName}" جاهز!\n\nالوصف:\n${userProjects[chatId].projectDescription}\n\nتفاصيل إضافية:\n${projectDetails.additionalInfo || 'لا توجد تفاصيل إضافية.'}`
            });

            bot.sendMessage(chatId, 'تم إرسال مشروعك بنجاح!');

            // Clean up temporary files
            fs.unlinkSync(zipFilePath);
            fs.rmSync(projectPath, { recursive: true, force: true });

        } catch (error) {
            console.error('Error during project creation:', error);
            bot.sendMessage(chatId, 'عذراً، حدث خطأ أثناء إنشاء مشروعك. يرجى المحاولة مرة أخرى لاحقاً.');
        } finally {
            delete userProjects[chatId]; // Clear user state
        }
    } else {
        bot.sendMessage(chatId, 'أنا هنا لإنشاء المشاريع! أرسل /newproject لبدء مشروع جديد.');
    }
});

// Placeholder for AI project generation
async function generateProject(projectName, projectDescription) {
    // In a real scenario, this would call an AI API (e.g., OpenAI, custom model)
    // to generate file structures, code snippets, and project details based on the description.
    console.log(`AI generating project: ${projectName} with description: ${projectDescription}`);

    // Simulate AI processing time
    await new Promise(resolve => setTimeout(resolve, 5000));

    // Return a mock project structure and content
    return {
        files: {
            'README.md': `# ${projectName}\n\n${projectDescription}\n\nThis project was generated by an AI bot.`,
            'src/index.js': `console.log('Hello from ${projectName}!');\n// AI-generated code will go here`,
            'public/index.html': `<!DOCTYPE html>\n<html>\n<head><title>${projectName}</title></head>\n<body><h1>Welcome to ${projectName}</h1><script src="../src/index.js"></script></body>\n</html>`
        },
        additionalInfo: 'تم إنشاء هذا المشروع كمثال بسيط. في المستقبل، سيقوم الذكاء الاصطناعي بإنشاء مشاريع أكثر تعقيداً.'
    };
}

// Function to create files and directories based on AI output
async function createProjectFiles(projectName, projectDetails) {
    const projectRoot = path.join(__dirname, 'projects', projectName);
    fs.mkdirSync(projectRoot, { recursive: true });

    for (const filePath in projectDetails.files) {
        const fullPath = path.join(projectRoot, filePath);
        const dirName = path.dirname(fullPath);
        fs.mkdirSync(dirName, { recursive: true });
        fs.writeFileSync(fullPath, projectDetails.files[filePath]);
    }
    return projectRoot;
}

// Function to zip the created project
async function zipProject(projectPath) {
    const outputFileName = `${path.basename(projectPath)}.zip`;
    const outputFilePath = path.join(__dirname, outputFileName);
    const output = fs.createWriteStream(outputFilePath);
    const archive = archiver('zip', {
        zlib: { level: 9 } // Sets the compression level.
    });

    return new Promise((resolve, reject) => {
        output.on('close', function () {
            console.log(archive.pointer() + ' total bytes');
            console.log('archiver has been finalized and the output file descriptor has closed.');
            resolve(outputFilePath);
        });

        archive.on('error', function (err) {
            reject(err);
        });

        archive.pipe(output);
        archive.directory(projectPath, false); // Append project directory to the archive
        archive.finalize();
    });
}
