import google.generativeai as genai
import asyncio
import json
import logging

from src.config import GEMINI_API_KEY

logger = logging.getLogger(__name__)

class AIService:
    def __init__(self):
        genai.configure(api_key=GEMINI_API_KEY)
        self.model = genai.GenerativeModel('gemini-pro')

    async def generate_project_content(self, project_name: str, project_description: str) -> dict:
        """Generate project files and content using Gemini AI."""
        logger.info(f"AI generating project: {project_name} with description: {project_description}")

        prompt = (
            f"You are an advanced AI project builder capable of creating real-world, functional projects. "
            f"Your task is to generate a complete project structure and content based on the user's request. "
            f"The output must be a JSON object with two keys: 'files' and 'additional_info'.\n"
            f"The 'files' key should contain a dictionary where keys are file paths (e.g., 'index.html', 'src/styles.css', 'backend/app.py') "
            f"and values are the content of those files. Ensure all necessary directories are implicitly created by the file paths.\n"
            f"The 'additional_info' key should contain a string with any extra details, setup instructions, "
            f"or commands the user might need to run the project (e.g., 'npm install', 'python -m venv .venv', 'flask run').\n\n"
            f"You have access to a wide range of tools and technologies to build projects, including but not limited to:\n"
            f"- Web Development: HTML, CSS, JavaScript (React, Vue, Angular, vanilla JS), Node.js (Express), Python (Flask, Django), PHP, Ruby on Rails.\n"
            f"- Backend Services: REST APIs, GraphQL, database schemas (SQL, NoSQL).\n"
            f"- Desktop Applications: Python (Tkinter, PyQt), Electron.\n"
            f"- Command-line Tools: Python scripts, Bash scripts.\n"
            f"- Configuration Files: Dockerfiles, package.json, requirements.txt, .env files.\n"
            f"- Documentation: README.md files with clear instructions.\n\n"
            f"Always strive to create a complete and runnable project. If a project requires dependencies, "
            f"include appropriate manifest files (e.g., `requirements.txt` for Python, `package.json` for Node.js) "
            f"and mention installation steps in `additional_info`. Ensure the project structure is logical and follows best practices for the chosen technologies.\n\n"
            f"Project Name: {project_name}\n"
            f"Project Description: {project_description}\n\n"
            f"Example output format:\n"
            f"{{\n"
            f"  \"files\": {{\n"
            f"    \"README.md\": \"# My Web App\\n\\nThis is a simple web application.\\n\\n## Setup\\n\\n`npm install`\\n`npm start`\",\n"
            f"    \"index.html\": \"<!DOCTYPE html>\\n<html><body><h1>Hello</h1></body></html>\",\n"
            f"    \"package.json\": \"{{\\\"name\\\": \\\"my-app\\\", \\\"version\\\": \\\"1.0.0\\\", \\\"scripts\\\": {{\\\"start\\\": \\\"node index.js\\\"}}}}\",\n"
            f"    \"index.js\": \"console.log('App started');\"\n"
            f"  }},\n"
            f"  \"additional_info\": \"To run this project, navigate to the project directory and run `npm install` followed by `npm start`.\"\n"
            f"}}\n\n"
            f"Please generate the project for: {project_name} with the description: {project_description}"
        )

        try:
            response = await asyncio.to_thread(self.model.generate_content, prompt)
            project_output = response.text.strip()

            if project_output.startswith('```json'):
                project_output = project_output.replace('```json', '').replace('```', '').strip()
            elif project_output.startswith('```'):
                project_output = project_output.replace('```', '').strip()

            project_data = json.loads(project_output)

            if 'files' not in project_data or not isinstance(project_data['files'], dict):
                raise ValueError("AI response missing 'files' dictionary or it's not a dictionary.")
            if 'additional_info' not in project_data or not isinstance(project_data['additional_info'], str):
                project_data['additional_info'] = 'AI did not provide additional information.'

            return project_data

        except Exception as e:
            logger.error(f"Error generating content with Gemini: {e}")
            return {
                'files': {
                    'README.md': f'# {project_name}\n\n{project_description}\n\nThis project was generated by an AI bot, but there was an error with the AI generation. Here is a default project.',
                    'src/error_project.txt': 'Could not generate project with AI. Please try again or refine your description.'
                },
                'additional_info': 'عذراً، حدث خطأ أثناء استخدام الذكاء الاصطناعي لإنشاء مشروعك. تم إنشاء مشروع افتراضي بسيط بدلاً من ذلك.'
            }
