import google.generativeai as genai
import asyncio
import json
import logging

from src.config import GEMINI_API_KEY

logger = logging.getLogger(__name__)

class AIService:
    def __init__(self):
        genai.configure(api_key=GEMINI_API_KEY)
        self.model = genai.GenerativeModel('gemini-pro')

    async def generate_project_content(self, project_name: str, project_description: str) -> dict:
        """Generate project files and content using Gemini AI."""
        logger.info(f"AI generating project: {project_name} with description: {project_description}")

        prompt = (
            f"You are an AI project builder. Your task is to generate a project structure and content "
            f"based on the user's request. The output should be a JSON object with two keys: 'files' and 'additional_info'.\n"
            f"The 'files' key should contain a dictionary where keys are file paths (e.g., 'src/main.py', 'README.md') "
            f"and values are the content of those files. Ensure all necessary directories are implicitly created by the file paths.\n"
            f"The 'additional_info' key should contain a string with any extra details or instructions for the user.\n\n"
            f"Project Name: {project_name}\n"
            f"Project Description: {project_description}\n\n"
            f"Example output format:\n"
            f"{{\n"
            f"  \"files\": {{\n"
            f"    \"README.md\": \"# My Project\\n\\nThis is a description.\",\n"
            f"    \"src/app.py\": \"print('Hello, World!')\"\n"
            f"  }},\n"
            f"  \"additional_info\": \"Here are some extra notes.\"\n"
            f"}}\n\n"
            f"Please generate the project for: {project_name} with the description: {project_description}"
        )

        try:
            response = await asyncio.to_thread(self.model.generate_content, prompt)
            project_output = response.text.strip()

            if project_output.startswith('```json'):
                project_output = project_output.replace('```json', '').replace('```', '').strip()
            elif project_output.startswith('```'):
                project_output = project_output.replace('```', '').strip()

            project_data = json.loads(project_output)

            if 'files' not in project_data or not isinstance(project_data['files'], dict):
                raise ValueError("AI response missing 'files' dictionary or it's not a dictionary.")
            if 'additional_info' not in project_data or not isinstance(project_data['additional_info'], str):
                project_data['additional_info'] = 'AI did not provide additional information.'

            return project_data

        except Exception as e:
            logger.error(f"Error generating content with Gemini: {e}")
            return {
                'files': {
                    'README.md': f'# {project_name}\n\n{project_description}\n\nThis project was generated by an AI bot, but there was an error with the AI generation. Here is a default project.',
                    'src/error_project.txt': 'Could not generate project with AI. Please try again or refine your description.'
                },
                'additional_info': 'عذراً، حدث خطأ أثناء استخدام الذكاء الاصطناعي لإنشاء مشروعك. تم إنشاء مشروع افتراضي بسيط بدلاً من ذلك.'
            }
